Add roles, routes for required pages, misc refactoring
RSP-Falcon-9/redact_frontend pull request #5
Opened 2019-11-20 21:47 UTC by JiriNenahlo

2019-11-20 21:48 UTC, JiriNenahlo commented
Prepared common article list component for all required roles, should speed up progress a lot after it's finished and merged.

2019-11-20 21:52 UTC, legas1 requested changes
WIP, do not merge

2019-11-22 15:18 UTC, legas1 requested changes

2019-11-22 15:18 UTC, legas1 commented on src/App.tsx
> +                        <PrivilegedRoute key="show_article_id" path="/article/:id" role="ROLE_AUTHOR" component={ArticleDetail} />
remove the key plz

2019-11-22 15:19 UTC, JiriNenahlo commented on src/App.tsx
> +                        <PrivilegedRoute key="show_article_id" path="/article/:id" role="ROLE_AUTHOR" component={ArticleDetail} />
fucking react

2019-11-22 15:20 UTC, legas1 approved these changes

2019-11-22 15:22 UTC, merged